<a href="https://colab.research.google.com/github/K-107/deep-learning-with-python-notebooks/blob/tf2/2.3-copy()_71p.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# x = x.copy()가 입력 텐서 자체를 바꾸지 않도록 복사를 한다!

즉, x = x.copy()를 하면 함수에 입력된 x를 유지하면서 함수로 계산된 return x가 나온다.

하지만 없다면 입력된 x의 값이 함수 계산된 return x와 같이 바껴버린다.


In [7]:
import numpy as np

def naive_relu(x):
  assert len(x.shape) == 2

  x = x.copy()

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j], 0)
  return x


def naive_relu_without_copy(x):
  assert len(x.shape) == 2

  # x = x.copy()

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j], 0)
  return x

In [8]:
a = np.array([[-1,4]])
a

array([[-1,  4]])

In [9]:
naive_relu(a), a
# 입력 a와 출력 a의 값이 다르다.
# 즉 입력 a가 보전되었다.

(array([[0, 4]]), array([[-1,  4]]))

In [10]:
naive_relu_without_copy(a), a
# 입력 a의 값이 바꼇다!

(array([[0, 4]]), array([[0, 4]]))